package info.superalsrk.model.core.entity;

// Generated 2013-5-27 15:56:23 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Forum generated by hbm2java
 */
@Entity
@Table(name = "forum", catalog = "bbs")
public class Forum implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Integer orderSequence;
	private List <Subforum> subforums = new ArrayList <Subforum>();

	public Forum() {
	}

	public Forum(String name, String description, List<Subforum> subforums) {
		this.name = name;
		this.description = description;
		this.subforums = subforums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 2028)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	
	@Column(name = "orderSequence")
	public Integer getOrderSequence() {
		return orderSequence;
	}

	public void setOrderSequence(Integer orderSequence) {
		this.orderSequence = orderSequence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "forum", cascade=CascadeType.REMOVE)
	public List<Subforum> getSubforums() {
		return this.subforums;
	}

	public void setSubforums(List<Subforum> subforums) {
		this.subforums = subforums;
	}

}
