package info.superalsrk.model.core.entity;

// Generated 2013-3-30 18:00:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Forum generated by hbm2java
 */
@Entity
@Table(name = "forum", catalog = "bbs")
public class Forum implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Set<Subforum> subforums = new HashSet<Subforum>(0);

	public Forum() {
	}

	public Forum(int id) {
		this.id = id;
	}

	public Forum(int id, String name, String description,
			Set<Subforum> subforums) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.subforums = subforums;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "forum")
	public Set<Subforum> getSubforums() {
		return this.subforums;
	}

	public void setSubforums(Set<Subforum> subforums) {
		this.subforums = subforums;
	}

}
