package info.superalsrk.model.core.entity;

// Generated 2013-5-27 15:56:23 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subforum generated by hbm2java
 */
@Entity
@Table(name = "subforum", catalog = "bbs")
public class Subforum implements java.io.Serializable {

	private Integer id;
	private Forum forum;
	private User user;
	private String name;
	private String description;
	private Integer replyLevel;
	private Integer postLevel;
	private Integer scanLevel;
	private Integer orderSequence;
	private List <Topic> topics = new ArrayList <Topic>();

	public Subforum() {
	}

	public Subforum(Forum forum, User user, String name, String description,
			Integer replyLevel, Integer postLevel, Integer scanLevel, List<Topic> topics) {
		this.forum = forum;
		this.user = user;
		this.name = name;
		this.description = description;
		this.replyLevel = replyLevel;
		this.postLevel = postLevel;
		this.scanLevel = scanLevel;
		this.topics = topics;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "forumId")
	public Forum getForum() {
		return this.forum;
	}

	public void setForum(Forum forum) {
		this.forum = forum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moderato")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 2028)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "replyLevel")
	public Integer getReplyLevel() {
		return this.replyLevel;
	}

	public void setReplyLevel(Integer replyLevel) {
		this.replyLevel = replyLevel;
	}

	@Column(name = "postLevel")
	public Integer getPostLevel() {
		return this.postLevel;
	}

	public void setPostLevel(Integer postLevel) {
		this.postLevel = postLevel;
	}

	@Column(name = "scanLevel")
	public Integer getScanLevel() {
		return this.scanLevel;
	}

	public void setScanLevel(Integer scanLevel) {
		this.scanLevel = scanLevel;
	}
	
	@Column(name = "orderSequence")
	public Integer getOrderSequence() {
		return orderSequence;
	}

	public void setOrderSequence(Integer orderSequence) {
		this.orderSequence = orderSequence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subforum", cascade=CascadeType.REMOVE)
	public List<Topic> getTopics() {
		return this.topics;
	}

	public void setTopics(List<Topic> topics) {
		this.topics = topics;
	}

}
