package info.superalsrk.model.core.entity;

// Generated 2013-5-27 15:56:23 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Topic generated by hbm2java
 */
@Entity
@Table(name = "topic", catalog = "bbs")
public class Topic implements java.io.Serializable {

	private Integer id;
	private Subforum subforum;
	private User user;
	private Date postTime;
	private Date lastreplyTime;
	private String topicContent;
	private List <Reply> replies = new ArrayList <Reply>();

	public Topic() {
	}

	public Topic(Subforum subforum, User user, Date postTime,
			Date lastreplyTime, String topicContent, List<Reply> replies) {
		this.subforum = subforum;
		this.user = user;
		this.postTime = postTime;
		this.lastreplyTime = lastreplyTime;
		this.topicContent = topicContent;
		this.replies = replies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subforum_id")
	public Subforum getSubforum() {
		return this.subforum;
	}

	public void setSubforum(Subforum subforum) {
		this.subforum = subforum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "originalPoster")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "postTime", length = 19)
	public Date getPostTime() {
		return this.postTime;
	}

	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastreplyTime", length = 19)
	public Date getLastreplyTime() {
		return this.lastreplyTime;
	}

	public void setLastreplyTime(Date lastreplyTime) {
		this.lastreplyTime = lastreplyTime;
	}

	@Column(name = "topicContent", length = 4048)
	public String getTopicContent() {
		return this.topicContent;
	}

	public void setTopicContent(String topicContent) {
		this.topicContent = topicContent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topic",cascade=CascadeType.REMOVE)
	public List<Reply> getReplies() {
		return this.replies;
	}

	public void setReplies(List<Reply> replies) {
		this.replies = replies;
	}

}
