package info.superalsrk.model.core.entity;

// Generated 2013-5-27 15:56:23 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "bbs")
public class User implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String password;
	private String email;
	private Integer score;
	private Integer currentLevel;
	private Date registerTime;
	private List <Topic> topics = new ArrayList <Topic>();
	private List <Reply> replies = new ArrayList <Reply>();
	private List <Subforum> subforums = new ArrayList <Subforum>();

	public User() {
	}

	public User(String userName, String password, String email, Integer score,
			Integer currentLevel, Date registerTime, List<Topic> topics, List<Reply> replies,
			List<Subforum> subforums) {
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.score = score;
		this.currentLevel = currentLevel;
		this.registerTime = registerTime;
		this.topics = topics;
		this.replies = replies;
		this.subforums = subforums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userName", length = 32)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", length = 64)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "currentLevel")
	public Integer getCurrentLevel() {
		return this.currentLevel;
	}

	public void setCurrentLevel(Integer currentLevel) {
		this.currentLevel = currentLevel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registerTime", length = 19)
	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public List<Topic> getTopics() {
		return this.topics;
	}

	public void setTopics(List<Topic> topics) {
		this.topics = topics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public List<Reply> getReplies() {
		return this.replies;
	}

	public void setReplies(List<Reply> replies) {
		this.replies = replies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public List<Subforum> getSubforums() {
		return this.subforums;
	}

	public void setSubforums(List<Subforum> subforums) {
		this.subforums = subforums;
	}

}
